obj-$(CONFIG_HTE)		+= hte.o
obj-$(CONFIG_HTE_TEGRA194)	+= hte-tegra194.o
obj-$(CONFIG_HTE_TEGRA194_IRQ_TEST) += hte-tegra194-irq-test.o
obj-$(CONFIG_HTE_TEGRA194_GPIO_TEST) += hte-tegra194-gpio-test.o

